# Generated by Django 4.2.1 on 2023-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('origen', models.CharField(max_length=100)),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
    ]
